### ISSUE TITLE
Installing wordpress causing conflict

### ISSUE THREAD

**Issue by hdfssk** [wesleytodd/YeoPress#132]
Running yeopress in a (new, empty) directory *always* reports a conflict after the wordpress installation, and prompts for resolution. 

* When the current wordpress is not in the yeoman cache:
```
> Installing WordPress 4.1
     info ... Fetching http://github.com/wordpress/wordpress/archive/4.1.tar.gz ...
     info This might take a few moments
.....✔ Done in ~/.cache/yeoman/wordpress/wordpress/4.1
>> WordPress installed
 conflict 
[?] Overwrite ? (Ynaxdh)
```
* When the current wordpress has already been cached:
```
>> Installing WordPress 4.1
>> WordPress installed
 conflict 
[?] Overwrite ? (Ynaxdh)
```

**Comment by wesleytodd** [comment]
I would love a PR that fixes this.  I am not really sure how to fix it because it is coming from the underlying implementation.  There is a ton of complexity under the hood here inside yeoman, and I didn't find a simple way.  

For now this is something I wont be fixing since it is as simple as responding `Y`.  But if you want to track down a solution I will merge and publish it right away.

**Comment by Toddses** [comment]
Just wanted to drop a note here, the pull request referenced is no longer relevant. Will be looking into alternate solutions for this one.

**Comment by wesleytodd** [comment]
see #134
