### ISSUE TITLE
Submodule Rage

### ISSUE THREAD

**Issue by wonderment** [wesleytodd/YeoPress#143]
By default, after running 'yo wordpress' with the Git and Submodule options added, should the 'wordpress' folder be marked as modified content?

We're having terrible issues trying to get this up to the remote repo and cloned because of all sorts of "fatal: reference is not a tree:" errors and things of that sort. I presume it's due to the submodule but can't figure it out.

We've tried:

$ yo wordpress
$ cd wordpress
$ git fetch --tags
$ git checkout 4.1.1 (the latest)
$ cd ..
$ git add wordpress
$ git commit -m "Latest WP."

and it fails miserably. I don't really have issues when it comes to adding WP as a submodule manually but for whatever reason with this particular generator setup, it just doesn't want to work. We're not the biggest submodule experts, either.

Thank you for any help.

**Comment by wonderment** [comment]
Not sure if it's operator error or what but checking out 4.1 and adding 'wordpress' to staging in the root folder seemed to smooth things out.

**Comment by wesleytodd** [comment]
The content should not be modified, but most likely it is just permissions.  The commands you are running seem fine.  Can you post more of the error information?

**Comment by wonderment** [comment]
Hi Wes,

Thank you for responding!

There's no error information, per se, but it is modified for 4.1.1 out of the gate.

Out of the gate meaning:

$ yo wordpress
$ www.test.dev
$ wp_
$ localhost
$ database-name
$ database-user
$ database-pass
$ Y (to use Git)
$ y (Wordpress as submodule)
$ wordpress (install dir)
$ content (content dir)
$ No (to use custom theme)
$ Yes (all is correct)

Here's an animated GIF of the procedure: http://i.imgur.com/5asMLbt.gif

I hope this helps!

**Comment by wonderment** [comment]
Navigating to the WordPress submodule folder and running the following gives me a working directory:

git clean -dfx
git reset --hard
git checkout 4.1.1

Possibly something was mixed in the submodule folder on this repo or the 4.1.1 branch needs to be updated?

**Comment by wesleytodd** [comment]
Did you check what it said was modified?  Was it permissions?  Because that is most likely, and really not an issue.

**Comment by wonderment** [comment]
I don't have it in front of me, but it was all of the files in the WP branch for 4.1.1. 

I'm not sure what is meant by permissions. Shouldn't running the yo wordpress generator have the submodule not modified out of the box? Past versions didn't seem to have this version and manually adding a WP submodule doesn't produce this problem.

**Comment by wonderment** [comment]
git config core.fileMode false from your previous issue works as well. Is this a system/OS issue as to why the permissions aren't being set?

**Comment by Toddses** [comment]
I have seen this and looked into it. It's the permissions being modified. I didn't change this behavior for 2.0.0 since it was behavior from the previous release. I have just avoided committing that change to the submodule.

I do agree in that I would think we wouldn't want to modify wordpress if installed as a submodule. Wouldn't the permissions changes be lost if a user pulls down a new branch?

**Comment by wesleytodd** [comment]
The permissions are being set because php/apache needs the files to have the right permissions.  Git tries to maintain file permissions across systems which often causes problems.  I imagine that is is considered best practice to set `fileMode` to `false` because of issues like this.

**Comment by wesleytodd** [comment]
FWIW, I always set that to false on all my machines because I have had serious issues with file permissions transitioning across to production environments and breaking things.  And also file permissions are system dependent and really not something I want my VCS to manage.

I am going to close this issue as a wont fix, but open a new issue to add a warning when doing this configuration that tells people to set fileMode to false.

**Comment by Toddses** [comment]
Learnt something new today. fileMode is where it's at.
