### ISSUE TITLE
Wordpress downloaded partially

### ISSUE THREAD

**Issue by dnzmsc** [wesleytodd/YeoPress#149]
Hi everyone, I have a weird problem.
Wordpress files are not entirely downloaded. I.e. I miss wp-settings.php, because the last file is wp-cron.php and inside wp-includes the last file is http.php, so I miss files like load.php and so on.

Anyone can help?
Thanks!

**Comment by wesleytodd** [comment]
See: https://github.com/wesleytodd/YeoPress/issues/147

That one was resolved by cleaning the yeoman cache.  There is a separate issue to log the errors correctly: https://github.com/wesleytodd/YeoPress/issues/148

**Comment by wesleytodd** [comment]
FYI, I closed your issue because there are already multiple issues chronicling this problem.  Before opening an issue you should use the search feature to look for similar issues.  When you find one adding a comment there is more helpful than starting your own.

In this case the search `is:issue missing files` found the exact issue I referenced above.  Maybe that isn't what you would have searched for, but In that case it was the most recently closed issue.  Just wanted to explain why I sent you here then promptly closed your issue.  :)
